# © 2019 TKOpen <https://tkopen.com>
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

{
    'name': 'FaturAqui Client',
    'summary': 'Issue invoices according to SAF-T (PT)',
    'description': 'Issue invoices according to SAF-T (PT)',
    'author': 'TKOpen',
    'category': 'Accounting',
    'license': 'LGPL-3',
    'website': 'https://tkopen.com',
    'version': '12.0.0.2',
    'support': 'info@tkopen.com',
    'sequence': 1,
    'depends': [
        'account',
        # 'account_cancel',
        'l10n_pt',
        # 'tko_first_login_change_password',
    ],
    'data': [
        # 'data/faturaqui_cron_view.xml',
        'wizard/account_invoice_cancel_view.xml',
        'wizard/account_move_reversal_view.xml',
        'wizard/sync_faturaqui_server_view.xml',
        'data/account_journal_data.xml',
        'data/account_tax_data.xml',
        'data/faturaqui_data.xml',
        'data/ir_actions_data.xml',
        'data/mail_template_data.xml',
        'security/ir.model.access.csv',
        'views/account_move_view.xml',
        'views/account_tax_view.xml',
        'views/account_view.xml',
        'views/faturaqui_view.xml',
        'views/product_view.xml',
        'views/res_partner_view.xml',
    ],
    'init_xml': [],
    'update_xml': [],
    'css': [],
    'demo_xml': [],
    'test': [],
    'external_dependencies': {
        'python': [
            'numpy',
        ],
        'bin': [],
    },
    'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
    'auto_install': False,
    'post_init_hook': '_faturaqui_post_init_hook',
}
